# Generated by Django 3.2.8 on 2021-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('student_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('student_email', models.EmailField(max_length=254)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('uid', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
