# Generated by Django 3.2.8 on 2021-10-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone_number',
            field=models.CharField(default=1212, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='zaid', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone_number',
            field=models.CharField(default=124234234, max_length=10),
            preserve_default=False,
        ),
    ]
