# Generated by Django 3.2.8 on 2021-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uid', models.CharField(max_length=64, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(default='Computer Science', max_length=20)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('marks_scored_percentage', models.FloatField()),
            ],
        ),
    ]
