# Generated by Django 3.2.8 on 2021-10-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_marklist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='student_man_name_61a91d_idx'),
        ),
    ]
